name: Parallel stability tests for parsers and host nodes.

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test. Default: main'
        required: true
        default: 'main'
      depthai-version:
        description: 'Version of depthai to install. Default: 3.0.0rc4'
        required: true
        default: '3.0.0rc4'
      duration:
        description: 'Duration of each test in seconds. Default: 10'
        required: true
        default: '10'
      distinct_id:
        description: 'Run identifier used for BOM.'
        required: false

jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}

  Stability-tests:
    runs-on: ['self-hosted', 'testbed-runner']

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install HIL
        run: |
          pip install hil_framework --upgrade --index-url https://__token__:${{ secrets.GITLAB_TOKEN }}@gitlab.luxonis.com/api/v4/projects/213/packages/pypi/simple

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: Run Parallel Tests
        run: |
          export RESERVATION_NAME="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          cd tests/stability_tests
          chmod +x ./parallel.sh
          ./parallel.sh
        env:
          GHCR_TOKEN: ${{secrets.GHCR_PAT}}
          GHCR_USER: ${{secrets.GHCR_USER}}
          LUXONIS_EXTRA_INDEX_URL: ${{secrets.LUXONIS_EXTRA_INDEX_URL}}
          DEPTHAI_VERSION: ${{ github.event.inputs.depthai-version }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          BRANCH: ${{ github.event.inputs.branch }}
          TEST_DURATION: ${{ github.event.inputs.duration }}
          RESERVATION_NAME: ${{ env.RESERVATION_NAME }}