name: Stability tests for parsers and host nodes.

on:
  workflow_dispatch:
    inputs:
      additional-parameter:
        description: 'Additional parameter: -all or -p <parser_name>. Default: -all. If -p is used: -p <parser_name>'
        required: true
        default: '-all --download'
      branch:
        description: 'Branch to test. Default: main'
        required: true
        default: 'main'
      depthai-version:
        description: 'Version of depthai to install. Default: alpha13'
        required: true
        default: '3.0.0a14'
      duration:
        description: 'Duration of each test in seconds. Default: 10'
        required: true
        default: '10'
      distinct_id:
        description: 'Run identifier used for BOM.'
        required: false

jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}

  Stability-tests:
    runs-on: ['self-hosted', 'testbed-runner']

    steps:
      - name: Update HIL
        run: |
          cd /home/$USER/hil_framework
          git pull
          git submodule update --init --recursive
 
      - name: Add HIL Tools to Path
        run: |
          cd /home/$USER/hil_framework
          echo "$(pwd)/lib_testbed/tools" >> $GITHUB_PATH
          echo "PYTHONPATH="$PYTHONPATH:$(pwd)"" >> $GITHUB_ENV
          echo "HIL_FRAMEWORK_PATH="$(pwd)"" >> $GITHUB_ENV

      - name: Run Test
        run: |
          export RESERVATION_NAME="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#${{ matrix.python-version}}"
          exec hil --testbed test --skip-sanity-check --stability-test --wait --reservation-name $RESERVATION_NAME --before-docker-pull "echo ${{secrets.GHCR_PAT}} | docker login ghcr.io -u ${{secrets.GHCR_USER}} --password-stdin" --docker-image ghcr.io/luxonis/depthai-nodes-stability-tests --docker-run-args '--env LUXONIS_EXTRA_INDEX_URL=${{secrets.LUXONIS_EXTRA_INDEX_URL}} --env DEPTHAI_VERSION=${{ github.event.inputs.depthai-version }} --env B2_APPLICATION_KEY=${{ secrets.B2_APPLICATION_KEY }} --env B2_APPLICATION_KEY_ID=${{ secrets.B2_APPLICATION_KEY_ID }} --env BRANCH=${{ github.event.inputs.branch }} --env FLAGS="${{ github.event.inputs.additional-parameter }} --duration ${{ github.event.inputs.duration }}"'